### ISSUE TITLE
Path.GetFileName does not correctly handle file names with : character

### ISSUE THREAD

**Issue by haacked** [FakeHaacked/git-demo#6]
On my machine, I added the following line to [this test](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/IO/Path.cs#L48).

``` csharp
Assert.Equal("file:name.exe", Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe")));
```

That test fails because `Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe"))` returns "name.exe".

That doesn't seem to be the correct behavior on any platform.

I'd expect this to either throw an exception (as it would in the case of "file|name.exe") OR I'd expect this to return "file:name.exe" since `:` is an allowed character in file names on non-Windows systems. Given the cross-platform goals of CoreFx, I assume the latter behavior is correct?

_As an aside, I noticed this repository contains [Path.cs](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/Path.cs) but that file is not included in the [project file](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System.Runtime.Extensions.CoreCLR.csproj)._

**Comment by FakeHaacked** [comment]
Have you tried turning it off an on again?
